version: "3.9"
services:
  caddy:
    image: caddy:2.7-alpine
    restart: always
    volumes:
      - ./html:/var/www/html
      - ./.caddy_data:/data
      - ./.caddy_config:/config
      - ./caddy/etc/Caddyfile:/etc/caddy/Caddyfile
      - ./caddy/etc/tls_auto:/etc/tls_auto
      - ./caddy/etc/tls_selfsigned:/etc/tls_selfsigned
    environment:
      - ACME_AGREE=true
    ports:
      - "2015:2015"
      - "80:80"
      - "443:443"
    env_file:
      - ./conf/caddy.env
    logging:
      driver: "json-file"
      options:
        max-size: "1M"
        max-file: "10"

  wp-fpm:
    image: wordpress:6-fpm
    restart: always
    links:
      - db
    depends_on:
      - db
    volumes:
      - html:/var/www/html
    env_file:
      - ./conf/wordpress.env
    logging:
      driver: "json-file"
      options:
        max-size: "1M"
        max-file: "10"

  db:
    image: mariadb:11-jammy
    restart: always
    volumes:
      - dbdata:/var/lib/mysql
    env_file:
      - ./conf/db.env
    logging:
      driver: "json-file"
      options:
        max-size: "1M"
        max-file: "10"

volumes:
  html:
    driver: local
    driver_opts:
      type: none
      device: $PWD/html 
      o: bind
  dbdata:
  elastic:
    driver: local
